### ISSUE TITLE
Q00 Format

### ISSUE THREAD

**Issue by sebastianhenaosanta** [mfassler/python3-quanergyM8#1]
Hey this is not an issue this more like a question, is there a way to transform this data to q00 format?

**Comment by mfassler** [comment]
I'm not sure what q00 format is.  Is that the native binary format of the Lidar?  I think you could just use socat or similar to capture the datastream to disk.  

This software converts the Quanergy data into Numpy arrays.  So if you can find some Numpy-related software, then you might be able to do it that way.
